INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de ensino', 'navigation.teaching_plans_menu', '', 'teaching_plans', 'module', '', 1, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de ensino por disciplina', 'navigation.discipline_teaching_plans', '', 'teaching_plans', 'module', '', 2, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de ensino por áreas de conhecimento', 'navigation.knowledge_area_teaching_plans', '', 'teaching_plans', 'module', '', 3, now(), now());

INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Unidade temática', 'activerecord.attributes.teaching_plan.thematic_unit', '', 'teaching_plans', 'fields', '', 4, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Campos de experiência', 'activerecord.attributes.teaching_plan.experience_fields', '', 'teaching_plans', 'fields', '', 5, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Objetivos (por disciplina)', 'activerecord.attributes.discipline_teaching_plan.objectives', '', 'teaching_plans', 'fields', '', 6, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Objetivos (por área)', 'activerecord.attributes.knowledge_area_teaching_plan.objectives', '', 'teaching_plans', 'fields', '', 7, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por área)', 'activerecord.attributes.knowledge_area_teaching_plan.contents', '', 'teaching_plans', 'fields', '', 8, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por disciplina)', 'activerecord.attributes.discipline_teaching_plan.contents', '', 'teaching_plans', 'fields', '', 9, now(), now());

INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de aula', 'navigation.lesson_plans_menu', '', 'lesson_plans', 'module', '', 10, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de aula por disciplina', 'navigation.discipline_lesson_plans', '', 'lesson_plans', 'module', '', 11, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Planos de aula por áreas de conhecimento', 'navigation.knowledge_area_lesson_plans', '', 'lesson_plans', 'module', '', 12, now(), now());

INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Unidade temática', 'activerecord.attributes.lesson_plan.thematic_unit', '', 'lesson_plans', 'fields', '', 13, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Campos de experiência', 'activerecord.attributes.lesson_plan.experience_fields', '', 'lesson_plans', 'fields', '', 14, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Objetivos (por disciplina)', 'activerecord.attributes.discipline_lesson_plan.objectives', '', 'lesson_plans', 'fields', '', 15, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Objetivos (por área)', 'activerecord.attributes.knowledge_area_lesson_plan.objectives', '', 'lesson_plans', 'fields', '', 17, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por área)', 'activerecord.attributes.knowledge_area_lesson_plan.contents', '', 'lesson_plans', 'fields', '', 18, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por disciplina)', 'activerecord.attributes.discipline_lesson_plan.contents', '', 'lesson_plans', 'fields', '', 19, now(), now());

INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Registros de conteúdos', 'navigation.content_records_menu', '', 'content_records', 'module', '', 20, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Registros de conteúdos por disciplina', 'navigation.discipline_content_records', '', 'content_records', 'module', '', 21, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Registros de conteúdos por áreas de conhecimento', 'navigation.knowledge_area_content_records', '', 'content_records', 'module', '', 22, now(), now());

INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por área)', 'activerecord.attributes.knowledge_area_content_record.contents', '', 'content_records', 'fields', '', 23, now(), now());
INSERT INTO translations ("label", "key", "translation", "group", "subgroup", "hint", "order", "created_at", "updated_at") VALUES ('Conteúdos (por disciplina)', 'activerecord.attributes.discipline_content_record.contents', '', 'content_records', 'fields', '', 24, now(), now());
