inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRailsVersion: 5.0
  Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 115

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false
