source 'https://rubygems.org'

ruby '2.2.6'

gem 'active_model_serializers'
gem 'activerecord-connections', git: 'https://github.com/ricardohsd/activerecord-connections.git'
gem 'activerecord-session_store'
gem 'activerecord-tableless', '~> 2.0'
gem 'angular_rails_csrf'
gem 'audited-activerecord', git: 'https://github.com/portabilis/audited.git'
gem 'aws-sdk', '~> 2'
gem 'backbone-nested-attributes', git: 'git://github.com/samuelsimoes/backbone-nested-attributes.git'
gem 'bulk_insert', '~> 1.0'
gem 'carrierwave'
gem 'cocoon', '~> 1.2.6'
gem 'cpf_cnpj'
gem 'decore', git: 'https://github.com/matiasleidemer/decore'
gem 'deferring'
gem 'devise', '3.5.1'
gem 'ejs', '~> 1.1', '>= 1.1.1'
gem 'enumerate_it', '1.3.1'
gem 'fog', '~> 1.36'
gem 'foreigner', '1.6.1'
gem 'handlebars_assets', '~> 0.23.0'
gem 'has_scope', '0.5.1'
gem 'honeybadger', '~> 3'
gem 'i18n_alchemy', '0.2.1', github: 'giustin/i18n_alchemy', branch: 'master'
gem 'jbuilder', '~> 2.2.2'
gem 'js-routes'
gem 'kaminari', '~> 0.16.1'
gem 'less-rails', '~> 2.7.1'
gem 'loofah', '~> 2.2.1'
gem 'mask_validator', '0.2.1'
gem 'mina', '1.2.3'
gem 'mina-puma', require: false,  github: 'untitledkingdom/mina-puma'
gem 'mina-sidekiq', '~> 1.0.3'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.8.1'
gem 'paperclip', '~> 5.2.0'
gem 'paranoia', '~> 2.2'
gem 'pg', '0.17.1'
gem 'postgres-copy'
gem 'prawn', '~> 2.1.0', github: 'portabilis/prawn', branch: 'master'
gem 'prawn-table', '0.2.2'
gem 'puma', '~> 3.12.0'
gem 'pundit', '0.3.0'
gem 'rack-cors', '~> 0.4.1 ', require: 'rack/cors'
gem 'rack-protection', '~> 1.5.5'
gem 'rails', '~> 4.2.7.1'
gem 'rake', '~> 11.1.0'
gem 'rdstation-ruby-client'
gem 'responders', '~> 2.0'
gem 'rest-client', git: 'https://github.com/ricardohsd/rest-client.git'
gem 'route_translator', git: 'https://github.com/enriclluelles/route_translator.git'
gem 'rubyzip', '~> 1.2.1', require: 'zip'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sidekiq', '< 6'
gem 'sidekiq-unique-jobs', '~> 4.0.18'
gem 'simple_form', '3.1.0'
gem 'sinatra', '>= 1.3.0', require: nil
gem 'therubyracer', '0.12.2'
gem 'twitter-bootstrap-rails', '3.2.0'
gem 'uglifier', '>= 1.3.0'
gem 'uri_validator'
gem 'validates_timeliness', '3.0.14'
gem 'zenvia-ruby', git: 'https://github.com/portabilis/zenvia-ruby'

group :development do
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'meta_request'
  gem 'pry-byebug'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'business_time'
  gem 'capybara', '~> 2.5'
  gem 'capybara-screenshot'
  gem 'cpf_faker', '~> 1.3'
  gem 'database_cleaner', '~> 1.5', '>= 1.5.1'
  gem 'factory_girl_rails', '~> 4.5'
  gem 'faker', '~> 1.6', '>= 1.6.1'
  gem 'pdf-inspector', require: 'pdf/inspector'
  gem 'poltergeist', '~> 1.8.1'
  gem 'pry', '~> 0.10.3'
  gem 'rspec-rails', '~> 3.4'
  gem 'rspec-sidekiq'
  gem 'rspec-wait', '~> 0.0.9'
  gem 'shoulda-matchers', '~> 3.0', '>= 3.0.1'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'turnip', '~> 1.3', '>= 1.3.1'
  gem 'vcr', '~> 3.0'
  gem 'webmock', '~> 1.22', '>= 1.22.3'
end

group :test, :development do
  gem 'bullet'
end

group :staging, :production do
  gem 'gelf'
  gem 'lograge'
end
