class Features < EnumerateIt::Base
  associate_values :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***s,
                   :***REMOVED***,
                   :***REMOVED***,
                   :unities,
                   :users,
                   :general_configurations,
                   :ieducar_api_configurations,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***_classes,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :moved_***REMOVED***,
                   :***REMOVED***,
                   :***REMOVED***,
                   :authorization_***REMOVED***,
                   :***REMOVED***_configs,
                   :***REMOVED***s,
                   :***REMOVED***_confirmations,
                   :roles,
                   :entity_configurations,
                   :test_settings,
                   :school_calendars,
                   :school_calendar_events,
                   :teaching_plans,
                   :contents,
                   :avaliations,
                   :daily_notes,
                   :daily_frequencies,
                   :absence_justifications,
                   :messages,
                   :conceptual_exams

  sort_by :translation
end
