class AddNewFieldsInBncc < ActiveRecord::Migration
  def change
    execute <<-SQL
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.methodology_by_discipline', 'Metodologia (por disciplina)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 25, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.methodology_by_knowledge_area', 'Metodologia (por área)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 26, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_discipline', 'Avaliação (por disciplina)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 27, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_knowledge_area', 'Avaliação (por área)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 28, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_discipline', 'Referências (por disciplina)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 29, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_knowledge_area', 'Referências (por área)', '', 'teaching_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 30, now(), now());

      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.actives_methodology_by_discipline', 'Atividades/metodologia (por disciplina)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 31, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.actives_methodology_by_knowledge_area', 'Atividades/metodologia (por área)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 32, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_discipline', 'Avaliação (por disciplina)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 33, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_knowledge_area', 'Avaliação (por área)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 34, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_discipline', 'Referências (por disciplina)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 35, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_knowledge_area', 'Referências (por área)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 36, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.resources_by_discipline', 'Recursos (por disciplina)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 37, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.resources_by_knowledge_area', 'Recursos (por área)', '', 'lesson_plans', 'fields', 'Altera o nome do módulo; o caminho da tela de Registros de conteúdos por áreas de conhecimento; título da listagem e do novo cadastro; cópia de registros', 38, now(), now());
    SQL
  end
end
