class AddNewFieldsInBncc < ActiveRecord::Migration[4.2]
  def change
    execute <<-SQL
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.methodology_by_discipline', 'Metodologia (por disciplina)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Metodologia dentro do cadastro de Planos de ensino por disciplina', 25, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.methodology_by_knowledge_area', 'Metodologia (por área)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Metodologia dentro do cadastro de Planos de ensino por área de conhecimento', 26, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_discipline', 'Avaliação (por disciplina)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Avaliação dentro do cadastro de Planos de ensino por disciplina', 27, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_knowledge_area', 'Avaliação (por área)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Avaliação dentro do cadastro de Planos de ensino por área de conhecimento', 28, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_discipline', 'Referências (por disciplina)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Referências dentro do cadastro de Planos de ensino por disciplina', 29, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_knowledge_area', 'Referências (por área)', '', 'teaching_plans', 'fields', 'Altera a nomenclatura do campo Referências dentro do cadastro de Planos de ensino por área de conhecimento', 30, now(), now());

      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.actives_methodology_by_discipline', 'Atividades/metodologia (por disciplina)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Atividades/metodologia dentro do cadastro de Planos de aula por disciplina', 31, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.actives_methodology_by_knowledge_area', 'Atividades/metodologia (por área)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Atividades/metodologia dentro do cadastro de Planos de aula por áreas de conhecimento', 32, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_discipline', 'Avaliação (por disciplina)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Avaliação dentro do cadastro de Planos de aula por disciplina', 33, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.avaliation_by_knowledge_area', 'Avaliação (por área)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Avaliação dentro do cadastro de Planos de aula por áreas de conhecimento', 34, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_discipline', 'Referências (por disciplina)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Referências dentro do cadastro de Planos de aula por disciplina', 35, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.references_by_knowledge_area', 'Referências (por área)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Referências dentro do cadastro de Planos de aula por áreas de conhecimento', 36, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.resources_by_discipline', 'Recursos (por disciplina)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Recursos dentro do cadastro de Planos de aula por disciplina', 37, now(), now());
      insert into translations(key, label, translation, "group", subgroup, hint, "order", created_at, updated_at) values ('navigation.resources_by_knowledge_area', 'Recursos (por área)', '', 'lesson_plans', 'fields', 'Altera a nomenclatura do campo Recursos dentro do cadastro de Planos de aula por áreas de conhecimento', 38, now(), now());
    SQL
  end
end
